version: 0.2

phases:
  install:
    commands:
      - echo installing server dependencies ...
      - npm run install-server
      - echo installing client dependencies ...
      - npm run install-client
  build: 
    commands:
      - echo building server ...
      - npm run build-server
      - echo building client ... 
      - npm run build-client
  post_build:
    commands:
      - ls -lah server 
      - ls -lah client
artifacts:
  files:
    - "**/*"
    - 'dist/**/*'
    - 'build/**/*'
    